/*
 * This file is generated by jOOQ.
 */
package com.gugu.dts.course.core.inf.jooq.database;


import com.gugu.dts.course.core.inf.jooq.database.tables.Course;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Dts extends SchemaImpl {

    private static final long serialVersionUID = -746846302;

    /**
     * The reference instance of <code>dts</code>
     */
    public static final Dts DTS = new Dts();

    /**
     * The table <code>dts.course</code>.
     */
    public final Course COURSE = Course.COURSE;

    /**
     * No further instances allowed
     */
    private Dts() {
        super("dts", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Course.COURSE);
    }
}
