/*
 * This file is generated by jOOQ.
 */
package com.gugu.dts.course.core.inf.jooq.database;


import com.gugu.dts.course.core.inf.jooq.database.tables.Course;


/**
 * Convenience access to all tables in dts
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>dts.course</code>.
     */
    public static final Course COURSE = Course.COURSE;
}
